### ISSUE TITLE
Allow to use Docker volume for Solr files

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue#437]
The Solr directory of databases (I think `/opt/solr/server/solr`) should be mountable when starting the solr container so the Solr index can be kept outside of Docker container.

**Comment by pkiraly** [comment]
I am investigating it. The difficulty I see here is that this directory might need some configuration files populated, e.g. the `configsets` directory.

**Comment by nichtich** [comment]
Attention: files created with `RUN` in `Dockerfile` will get ignored when their directory is later exposed as volume, so the files need to be created when the container is started, not as part of the image.

**Comment by Phu2** [comment]
Currently, all Solr data is lost when the container is stopped and removed, eg. by executing `docker compose down`

**Comment by Phu2** [comment]
How about using a separate container for Solr from the official image rather than manually install it in the same container? This way it is easier to persist data on the host. The `docker-compose.yml` would look like:

```
# Used to start the base image with `docker compose up -d`

version: '2'

services:
  solr:
    image: solr:8.11.3
    ports:
      - "8983:8983"
    volumes:
      # Create directory up front with the right permissions, eg.: mkdir ./solr && chown -R 8983:8983 ./solr
      - ./solr:/var/solr
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:8983",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    restart: on-failure
    networks:
      - qa-catalogue-backend

  app:
    depends_on:
      solr:
        condition: service_healthy
    container_name: metadata-qa-marc
    # image: ${IMAGE:-pkiraly/metadata-qa-marc:0.7.0}
    # image: ghcr.io/pkiraly/qa-catalogue:main
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./${INPUT:-input}:/opt/qa-catalogue/input
      - ./${OUTPUT:-output}:/opt/qa-catalogue/output
      - ./catalogues:/opt/qa-catalogue/catalogues
      - ./${WEBBCONFIG:-web-config}:/var/www/html/qa-catalogue/config
    ports:
      - "${WEBPORT:-8000}:80"       # qa-catalogue-web
      # - "${SOLRPORT:-8983}:8983"  # Solr
    networks:
      - qa-catalogue-backend

networks:
  qa-catalogue-backend:
    name: qa-catalogue-backend
    external: true
```
However, the indexing scripts have to be adapted in order to talk to the Solr container (not localhost).
